export const AUDIT_ACTIONS = Object.freeze({
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",

  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",

  DEPARTMENT_CREATED: "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED: "DEPARTMENT_UPDATED",
  DEPARTMENT_STATUS_CHANGED: "DEPARTMENT_STATUS_CHANGED",

  LEAVE_TYPE_CREATED: "LEAVE_TYPE_CREATED",
  LEAVE_TYPE_UPDATED: "LEAVE_TYPE_UPDATED",
  LEAVE_TYPE_STATUS_CHANGED: "LEAVE_TYPE_STATUS_CHANGED",

  HOLIDAY_CREATED: "HOLIDAY_CREATED",
  HOLIDAY_UPDATED: "HOLIDAY_UPDATED",
  HOLIDAY_STATUS_CHANGED: "HOLIDAY_STATUS_CHANGED",

  LEAVE_SUBMITTED: "LEAVE_SUBMITTED",
  LEAVE_CANCELLED: "LEAVE_CANCELLED",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",

  LEAVE_BALANCE_ADJUSTED: "LEAVE_BALANCE_ADJUSTED",
});

export const AUDIT_ACTION_VALUES = Object.values(AUDIT_ACTIONS);

export const AUDIT_ENTITY_TYPES = Object.freeze({
  AUTH: "AUTH",
  USER: "USER",
  DEPARTMENT: "DEPARTMENT",
  LEAVE_TYPE: "LEAVE_TYPE",
  HOLIDAY: "HOLIDAY",
  LEAVE_REQUEST: "LEAVE_REQUEST",
  LEAVE_BALANCE: "LEAVE_BALANCE",
});

export const AUDIT_ENTITY_TYPE_VALUES = Object.values(AUDIT_ENTITY_TYPES);
