export const NOTIFICATION_TYPES = Object.freeze({
  LEAVE_SUBMITTED: "LEAVE_SUBMITTED",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",
  LEAVE_CANCELLED: "LEAVE_CANCELLED",
  BALANCE_ADJUSTED: "BALANCE_ADJUSTED",
  SYSTEM: "SYSTEM",
});

export const NOTIFICATION_TYPE_VALUES = Object.values(NOTIFICATION_TYPES);
